Zero  fun

In [ ]:
import numpy as np

arr = np.zeros((3,2)) # need to provide the size inside a tuple
arr

one function

In [3]:
import numpy as np

arr = np.ones((3,2)) # need to provide the size inside a tuple
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

eye - to make the diagonal element 1

In [10]:
import numpy as np

arr = np.eye(3,4) # need to provide the size inside a tuple
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

diag - if you pass the elements, it will put them all in the diagona; and replace all the elements with zero

In [12]:
import numpy as np

arr = np.diag([3,4]) # elements, passing as list
arr

array([[3, 0],
       [0, 4]])

how to get the diagonal emenets of a 2d array

In [13]:
import numpy as np
list1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr= np.array(list1)
np.diag(arr)

array([1, 5, 9])

rand - create matrix of random number

In [15]:
import numpy as np

arr = np.random.rand(2,3)
arr

array([[0.27714586, 0.44821519, 0.02807643],
       [0.88395645, 0.41301174, 0.9456169 ]])

randn - 