sysntax : arr[row_range, col_range]

In [5]:
import numpy as np
list1 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr= np.array(list1)
arr[:2,1:3]

array([[2, 3],
       [5, 6]])

lets work with some big number

In [7]:
import numpy as np
np.random.seed(111)
arr = np.random.randint(1,500,30).reshape(6,5)
print(arr)

[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]


In [20]:
arr[3:5,2:]

array([[369, 217, 285],
       [ 22,  55, 201]])