everse an array

In [1]:
import numpy as np
list1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr= np.array(list1)

print(arr[::-1])

[7 6 5 4 3 2 1]


In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[::-1])

[[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [8]:
import numpy as np
list1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr= np.array(list1)

print(arr[::3])

[1 4 7]
